version: '3.8'

services:
#  web:
#    build: ./Exam_q
#    command: python manage.py runserver 0.0.0.0:8000
#    volumes:
#      - ./Exam_q/:/usr/src/app/
#    ports:
#      - 1337:8000
#    environment:
#      - DEBUG=1
#      - SECRET_KEY=dbaa1_i7%*3r9-=z-+_mz4r-!qeed@(-a_r(g@k8jo8y3r27%m
#      - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
#      - CELERY_BROKER=redis://redis:6379/0
#      - CELERY_BACKEND=redis://redis:6379/0
#    depends_on:
#      - redis

  celery:
    user: nobody
    build: ./Exam_q
    command: celery worker --app=Exam_q --loglevel=info --concurrency=1 -Q tasks_queue -E
    volumes:
      - ./Exam_q:/usr/src/app
    environment:
      - C_FORCE_ROOT=true
      - DEBUG=1
      - SECRET_KEY=dbaa1_i7%*3r9-=z-+_mz4r-!qeed@(-a_r(g@k8jo8y3r27%m
      - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
      - CELERY_BROKER=redis://redis:6379/0
      - CELERY_BACKEND=redis://redis:6379/0
    depends_on:
#      - web
      - redis

  redis:
    image: redis:5-alpine
    ports:
      - "6379:6379"


