# Generated by Django 4.0.4 on 2022-06-25 08:02

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=200)),
                ('title', models.TextField()),
                ('stats', jsonfield.fields.JSONField()),
            ],
        ),
    ]
