# Generated by Django 4.0.4 on 2022-06-25 08:07

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('exam_questions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='questions_pool',
            field=jsonfield.fields.JSONField(default={}),
            preserve_default=False,
        ),
    ]
