# Generated by Django 4.0.4 on 2022-06-25 09:45

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('exam_questions', '0002_file_questions_pool'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='params',
            field=jsonfield.fields.JSONField(default='{}'),
        ),
        migrations.AddField(
            model_name='file',
            name='tickets',
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='file',
            name='questions_pool',
            field=jsonfield.fields.JSONField(default={}),
        ),
    ]
