# Generated by Django 4.0.4 on 2022-06-25 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_questions', '0003_file_params_file_tickets_alter_file_questions_pool'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='output_format',
            field=models.CharField(default='.PDF', max_length=200),
        ),
    ]
