# Generated by Django 4.0.4 on 2022-06-25 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_questions', '0004_file_output_format'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='output_format',
            field=models.CharField(default='PDF', max_length=200),
        ),
    ]
