# Generated by Django 4.1 on 2022-08-23 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_questions', '0005_alter_file_output_format'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='uuid',
            field=models.CharField(default=2, max_length=200),
            preserve_default=False,
        ),
    ]
