# Generated by Django 4.0.4 on 2022-08-24 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_questions', '0006_file_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='uuid',
            field=models.CharField(default='none', max_length=200),
        ),
    ]
